sudo: false
language: node_js
node_js:
  - "6"
  - "7"
  - "8"

os:
  - osx

install:
  - npm prune
  - npm install
  - cd packages/skpm && npm prune && npm install && cd ../..
  - cd packages/builder && npm prune && npm install && cd ../..
  - cd packages/utils && npm prune && npm install && cd ../..
  - cd packages/test-runner && npm prune && npm install && cd ../..
  - cd packages/babel-preset && npm prune && npm install && cd ../..

cache:
  directories:
    - node_modules
    - packages/skpm/node_modules
    - packages/builder/node_modules
    - packages/utils/node_modules
    - packages/test-runner/node_modules
    - packages/babel-preset/node_modules

before_install:
  - npm set progress=false
